### ISSUE TITLE
Why iOS only?

### ISSUE THREAD

**Issue by maxsz** [apollostack/apollo-ios#10]
Hi,

great work! 👍

I was wondering why you're limiting this to iOS and not support swift in general (iOS, macOS, potentially Linux)? I could not find any iOS specific code? Would you be open to pull requests targeting general swift support (not only iOS)?

Background: We're currently evaluating existing swift/objc-based graphQL libraries for a macOS deployment target.

Thanks,
Max

**Comment by martijnwalraven** [comment]
Thanks! We're not intentionally limiting this to iOS, so we're definitely open to pull requests adding additional platform support. In fact, [we merged support for Swift Package Manager](https://github.com/apollostack/apollo-ios/pull/8) just last week, and the contributor mentioned he had gotten things to work server-side with the Kitura web framework.

Support for macOS should be especially easy to add, because as you write there isn't much iOS specific code in there right now.

Calling the project Apollo iOS reflects what the majority of developers will be using it for, and makes it easy to find for them. But I agree that can be confusing for macOS or server-side Swift developers.

There is always the issue of naming Cocoa projects, and things have gotten even more complicated with the addition of non-Cocoa targets for Swift.

I didn't want to name the project `apollo-swift` because I wanted to leave open the possibility of supporting Objective-C (and someone is in fact [working on an Objective-C target](https://github.com/KieranLafferty/apollo-codegen)).

**Comment by maxsz** [comment]
That sounds perfect 👍

**Comment by fruitcoder** [comment]
Does closing the issue mean it already supports watchOS/tvOS?

**Comment by martijnwalraven** [comment]
Closing this, because we now support both iOS and macOS, and also have targets for tvOS and watchOS (untested).
