### ISSUE TITLE
.sh file in build output prevents signing

### ISSUE THREAD

**Issue by qubitron** [apollostack/apollo-ios#27]
In the latest versions of Xcode, any file in the build output starting with an #! will result in an error when attempting to sign your app and upload to the store (as documented in [this stackoverflow question](http://stackoverflow.com/questions/29859996/error-itms-90035)). This is problematic because the Apollo deploys a the ```check-and-run-apollo-codegen.sh``` script to the build folder which is used in the build process, and the error when publishing just indicates that an object was not signed provides nothing to indicate what the problem is.

To work around this problem, I added a line at the end of the build step given in the [installation documentation](http://dev.apollodata.com/ios/installation.html) that removes the .sh file after codegen was completed:

```
APOLLO_FRAMEWORK_PATH=$(eval find $FRAMEWORK_SEARCH_PATHS -name "Apollo.framework" -maxdepth 1)

if [ -z "$APOLLO_FRAMEWORK_PATH" ]; then
echo "error: Couldn't find Apollo.framework in FRAMEWORK_SEARCH_PATHS; make sure to add the framework to your project."
exit 1
fi

cd ${SRCROOT}/${TARGET_NAME}
$APOLLO_FRAMEWORK_PATH/check-and-run-apollo-codegen.sh generate $(find . -name '*.graphql') --schema schema.json --output API.swift

rm $APOLLO_FRAMEWORK_PATH/check-and-run-apollo-codegen.sh
```

It would be very beneficial to anyone who wants to publish their app if you could update the documentation to include the last line of code, and/or set the build script up in a way that does not result in an .sh file being put in the build output.

**Comment by martijnwalraven** [comment]
Thanks for pointing out that the codesigning issue happens because of the shebang!

I actually just merged a pull request from @maxsz yesterday that fixes this issue by moving the script out of the framework. But the downside of that is that it requires special handling for CocoaPods and Carthage, and that existing users will have to change their Apollo "Run Script" phase.

It seems like removing the shebang should be enough, so we don't have to move the script out after all. Could you confirm this is working for you?

**Comment by qubitron** [comment]
@martijnwalraven I will test this out in the next day or so, thank you for the quick response!

**Comment by qubitron** [comment]
@martijnwalraven confirmed, removing the shebang fixed the signing problem for me
